### ISSUE TITLE
Booking System Calendar must be inclusive of current date

### ISSUE THREAD

**Issue by kierhickey** [mcscapstone/MCSCapstone#1]
Can we change this so users can book ahead time (ie. prior to start of academic calendar)

**Comment by samtimmins** [comment]
@kierhickey Can you elaborate a bit more on this? I can set the Academic Calendar for 1/1/2016 - 31/12/2030 without any problems, and it is simple enough to extend the calendar (if it was still in use) at this time to allow later dates. I did notice however, that I can make a booking for a date that has passed, is that what you mean by making the Calendar inclusive of the current date?

**Comment by kierhickey** [comment]
When the system is first installed if the database is not populated with an academic calendar / no bookings then the errors occur. This will only happen once.

**Comment by kierhickey** [comment]
To replicate, install the code on a clean system (a local host instance?) And before you do anything try accessing the booking page.

**Comment by samtimmins** [comment]
Ok thanks. Is it really a problem though? Considering we will be making sure that the Calendar is set up, and testing the system with bookings during implementation. Plus, importing bookings from the previous system?
