### ISSUE TITLE
Black Line in room 1 image, not visible in actual image?

### ISSUE THREAD

**Issue by kierhickey** [mcscapstone/MCSCapstone#12]
Please tell me I'm not crazy, but there seems to be a black computer generated line just above the sofa in room 1's image tile, it does not appear when the full image is shown?

![mcs-blackline](https://cloud.githubusercontent.com/assets/14848242/19020863/02de0d0a-8900-11e6-835e-57dd88494256.PNG)

**Comment by aaronjamesmarshallau** [comment]
Multiple images are used to display at the different image sizes. The small one used for that thumbnail (images/room1.jpg) does seem to have a random line drawn on it?

**Comment by aaronjamesmarshallau** [comment]
Hah. It's even there on the live site... http://melbourneconsultingsuites.com.au/index-3.html

**Comment by samtimmins** [comment]
I resized a copy of the larger image, so now the black line has been officially rubbed out.
