### ISSUE TITLE
Adding Closure dates/holidays

### ISSUE THREAD

**Issue by samtimmins** [mcscapstone/MCSCapstone#14]
In the "add holiday" section, if you try to choose a date without putting a name for the 'Holiday' in, the dates default to 01/01/1970

![image](https://cloud.githubusercontent.com/assets/22340401/19713963/f4596376-9b95-11e6-82bb-9cc349eac3f2.png)

**Comment by kierhickey** [comment]
Don't think will be a big issue, also don't have time to fix/not a priority...
