### ISSUE TITLE
Verification screens formatting

### ISSUE THREAD

**Issue by samtimmins** [mcscapstone/MCSCapstone#16]
![image](https://cloud.githubusercontent.com/assets/22340401/19714521/afe9fee4-9b9a-11e6-8c8e-abb61072313d.png)

The formatting for the verification page when wanting to delete something is pretty wonky. Not exactly a critical feature, but just to be aware of :)

**Comment by kierhickey** [comment]
Change that to red for both? and what's going on with the yes/no buttons?
