### ISSUE TITLE
insecure scripts cause CSS change, TODO: secure scripts or remove?

### ISSUE THREAD

**Issue by kierhickey** [mcscapstone/MCSCapstone#9]
Firefox blocks insecure scripts at https://mcstest.herokuapp.com/bookings/index.php/login
This causes CSS changes.

console output:
Blocked loading mixed active content “http://mcstest.herokuapp.com/bookings/webroot/style.css”
Blocked loading mixed active content “http://mcstest.herokuapp.com/bookings/webroot/print.css”
Blocked loading mixed active content “http://mcstest.herokuapp.com/bookings/webroot/sorttable.css”
Blocked loading mixed active content “http://mcstest.herokuapp.com/bookings/webroot/js/prototype.lite.js”
Blocked loading mixed active content “http://mcstest.herokuapp.com/bookings/webroot/js/util.js”
Blocked loading mixed active content “http://mcstest.herokuapp.com/bookings/webroot/js/sorttable.js”
Loading mixed (insecure) display content “http://mcstest.herokuapp.com/bookings/webroot/images/bg/global.png” on a secure page
Password fields present in a form with an insecure (http://) form action. This is a security risk that allows user login credentials to be stolen.

**Comment by kierhickey** [comment]
Also Blocked loading mixed active content “http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300”

**Comment by samtimmins** [comment]
I can no longer seem to replicate this error, did someone beat me to it?

**Comment by kierhickey** [comment]
font blocking still occurs. change or remove font?

**Comment by kierhickey** [comment]
font is now stored locally
